name: Node.js CI

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
  pull_request:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust Node.js version as needed

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
